# Iteration 

In [1]:
import numpy as np

In [3]:
var=np.array([1,2,3,4,5,6])
print(var)

for i in var:
    print(i)

[1 2 3 4 5 6]
1
2
3
4
5
6


In [5]:
var1=np.array([[32,4,2,32,57],[3,4,73,57,8]])
print(var1)
print()

for i in var1:
    print(i)

for k in var1:
    for j in k :
        print(j)

[[32  4  2 32 57]
 [ 3  4 73 57  8]]

[32  4  2 32 57]
[ 3  4 73 57  8]
32
4
2
32
57
3
4
73
57
8


In [6]:
var2=np.array([[[2,3,1,3,5],[3,6,85,25,2],[3,34,8,1,7]]])
print(var2)

for i in var2:
    for j in i:
        for k in j:
            print(k)

[[[ 2  3  1  3  5]
  [ 3  6 85 25  2]
  [ 3 34  8  1  7]]]
2
3
1
3
5
3
6
85
25
2
3
34
8
1
7


In [7]:
var2=np.array([[[2,3,1,3,5],[3,6,85,25,2],[3,34,8,1,7]]])
print(var2)

for i in np.nditer(var2):
    print(i)

[[[ 2  3  1  3  5]
  [ 3  6 85 25  2]
  [ 3 34  8  1  7]]]
2
3
1
3
5
3
6
85
25
2
3
34
8
1
7


In [9]:
var2=np.array([[[2,3,1,3,5],[3,6,85,25,2],[3,34,8,1,7]]])
print(var2)

for i in np.nditer(var2, flags=['buffered'], op_dtypes=['S']):
    print(i)

[[[ 2  3  1  3  5]
  [ 3  6 85 25  2]
  [ 3 34  8  1  7]]]
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'1')
np.bytes_(b'3')
np.bytes_(b'5')
np.bytes_(b'3')
np.bytes_(b'6')
np.bytes_(b'85')
np.bytes_(b'25')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'34')
np.bytes_(b'8')
np.bytes_(b'1')
np.bytes_(b'7')


In [12]:
var2=np.array([[[2,3,1,3,5],[3,6,85,25,2],[3,34,8,1,7]]])
print(var2)

for i,d in np.ndenumerate(var2):
    print(i,d)

[[[ 2  3  1  3  5]
  [ 3  6 85 25  2]
  [ 3 34  8  1  7]]]
(0, 0, 0) 2
(0, 0, 1) 3
(0, 0, 2) 1
(0, 0, 3) 3
(0, 0, 4) 5
(0, 1, 0) 3
(0, 1, 1) 6
(0, 1, 2) 85
(0, 1, 3) 25
(0, 1, 4) 2
(0, 2, 0) 3
(0, 2, 1) 34
(0, 2, 2) 8
(0, 2, 3) 1
(0, 2, 4) 7
