# Joins

In [1]:
import numpy as np

In [2]:
a1=np.array([1,2,3,4])
a2=np.array([5,6,7,8])
var=np.concatenate((a1,a2))
print(var)

[1 2 3 4 5 6 7 8]


In [3]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])
var=np.concatenate((a1,a2),axis=1)
print(var)

[[1 2 5 6]
 [3 4 7 8]]


In [4]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])
var=np.concatenate((a1,a2),axis=0)
print(var)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [9]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])
var=np.stack((a1,a2))
print(var)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [10]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])
var=np.hstack((a1,a2))
print(var)

[[1 2 5 6]
 [3 4 7 8]]


In [11]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])
var=np.vstack((a1,a2))
print(var)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [12]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])
var=np.dstack((a1,a2))
print(var)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


# Split

In [17]:
a1=np.array([1,2,3,4,5,6,7,8])
var=np.array_split(a1,4)
print(var)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In [21]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

newarr

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [24]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [25]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [26]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [27]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
