# Arrays

# NumPy is used to work with arrays. The array object in NumPy is called ndarray.
# We can create a NumPy ndarray object by using the array() function.

In [1]:
import numpy as np

# Types Of Arrays 

# 1D Array

In [9]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


# 2D Array

In [2]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


# 3D Array

In [3]:
arr1 = np.array([[[1,2,3],[4,5,6],[7,8,9],[1,2,4]]])
print(arr1)

[[[1 2 3]
  [4 5 6]
  [7 8 9]
  [1 2 4]]]


# Dimension
# NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [4]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [5]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a)
print(b)
print(c)
print(d)

42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [6]:
a=[]
for i in range(1,6):
    b=int(input("Enter Value: "))
    a.append(b)
print(np.array(a))

Enter Value:  24
Enter Value:  24
Enter Value:  15
Enter Value:  17
Enter Value:  83


[24 24 15 17 83]


In [12]:
arr2=np.array([1,2,3,4],ndmin=15)
print(arr2)
print(arr2.ndim)

[[[[[[[[[[[[[[[1 2 3 4]]]]]]]]]]]]]]]
15
