# Special Arrays

# Zero

In [2]:
import numpy as np

In [3]:
arr_zero=np.zeros(3)
print(arr_zero)

[0. 0. 0.]


In [5]:
arr_zero=np.zeros((3,3))
print(arr_zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Ones 

In [6]:
arr_ones=np.ones(5)
print(arr_ones)

[1. 1. 1. 1. 1.]


In [8]:
arr_ones=np.ones((3,4))
print(arr_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# Range

In [9]:
arr_range=np.arange(5)
print(arr_range)

[0 1 2 3 4]


# Diagonal

In [11]:
arr_diagonal=np.eye(3)
print(arr_diagonal)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
arr_diagonal=np.eye(3,6)
print(arr_diagonal)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]


# Linspace

In [14]:
arr_linspace=np.linspace(0,20,num=5)
print(arr_linspace)

[ 0.  5. 10. 15. 20.]
