# Random

In [1]:
import numpy as np

# Rand()

In [2]:
var=np.random.rand(8)
print(var)

[0.82936749 0.63865423 0.82369451 0.74070254 0.70098971 0.16355819
 0.98810858 0.45009491]


In [3]:
var=np.random.rand(4,4)
print(var)

[[0.84087666 0.40372805 0.79806507 0.88535504]
 [0.05948268 0.00871524 0.95778584 0.38483991]
 [0.23656703 0.14612654 0.13132266 0.9970257 ]
 [0.75961131 0.62109527 0.22531954 0.60782901]]


# Randn()

In [4]:
var1=np.random.randn(5)
print(var1)

[-0.73817769  0.24786241 -0.90968183 -0.6837235   0.2863268 ]


# Ranf()

In [7]:
var2=np.random.ranf(5)
print(var2)

[0.98254631 0.0778564  0.87229892 0.28095572 0.08699816]


# RandInt()

In [8]:
var3=np.random.randint(1,20,5)
print(var3)

[10  5 14 11  7]


# Choice()

In [11]:
var4=np.random.choice(["Ali","Ahmed","Noman","sawban","Ammar"])
print(var4)

Ali
