# Data Types

In [1]:
import numpy as np

In [8]:
var=np.array([1,334,52,24,5,3])

In [9]:
print(var.dtype)

int64


In [10]:
var=np.array([1.23,2.4,2.0])
print(var.dtype)

float64


In [11]:
var=np.array(["A","V","E"])
print(var.dtype)

<U1


In [13]:
var=np.array(["A","V","E",2,2,6])
print(var.dtype)

<U21


In [14]:
var=np.array(["Apple","banana","Grapes"])
print(var.dtype)

<U6


In [17]:
a=np.array([1,2,3,4,5],dtype=np.int8)
print(a.dtype)

int8


In [20]:
a=np.array([1,2,3,4,5],dtype="f")
print(a.dtype)
print(a)

float32
[1. 2. 3. 4. 5.]


In [22]:
var1=np.array([1,2,3,4])
new_var=np.float16(var1)
new1_var=np.int_(new_var)

print("Data Type: ",var.dtype)
print("Data Type: ",new_var.dtype)
print("Data Type: ",new1_var.dtype)

print(var1)
print(new_var)
print(new1_var)

Data Type:  <U6
Data Type:  float16
Data Type:  int64
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


In [23]:
x=np.array([1,2,3,4,5])
x1=x.astype(float)
print(x)
print(x1)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]
