# Shape

# The shape of an array is the number of elements in each dimension.



In [1]:
import numpy as np

In [5]:
var=np.array([[1,2,3,4],[5,6,7,8]])
print(var)
print(var.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [7]:
var=np.array([1,2,3,4],ndmin=5)
print(var)
print(var.shape)
print(var.ndim)

[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)
5


# Reshaping

In [9]:
var = np.array([1, 2, 3, 4, 5, 6])
new_var = var.reshape(3,2)

print(new_var)

[[1 2]
 [3 4]
 [5 6]]


In [10]:
var1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

new_var1 = var1.reshape(4, 3)

print(new_var1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [14]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(a)
print(a.ndim)
print("-"*10)
a1= a.reshape(4, 3)
print(a1)
print(a1.ndim)
print("-"*10)
a2=a1.reshape(-1)
print(a2)
print(a2.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
----------
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2
----------
[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
