# Arithmetic Operation

In [1]:
import numpy as np 

# Add

In [2]:
var=np.array([2,3,6,2])
var_add=var+5
print(var_add)

[ 7  8 11  7]


In [3]:
a1=np.array([1,2,3,4])
a2=np.array([5,6,7,8])
var1=a1+a2
print(var1)

[ 6  8 10 12]


In [15]:
a1=np.array([1,2,3,4])
a2=np.array([5,6,7,8])
var1=np.add(a1,a2)
print(var1)

[ 6  8 10 12]


# Sub

In [4]:
var=np.array([2,3,6,2])
var_sub=var-5
print(var_sub)

[-3 -2  1 -3]


In [5]:
a1=np.array([1,2,3,4])
a2=np.array([5,6,7,8])
var1=a1-a2
print(var1)

[-4 -4 -4 -4]


# Multiply

In [7]:
var=np.array([2,3,6,2])
var_mul=var*5
print(var_mul)

[10 15 30 10]


In [8]:
a1=np.array([1,2,3,4])
a2=np.array([5,6,7,8])
var1=a1*a2
print(var1)

[ 5 12 21 32]


# Divide 

In [10]:
var=np.array([2,3,6,2])
var_div=var/5
print(var_div)

[0.4 0.6 1.2 0.4]


In [11]:
a1=np.array([1,2,3,4])
a2=np.array([5,6,7,8])
var1=a1/a2
print(var1)

[0.2        0.33333333 0.42857143 0.5       ]


# Modulus

In [13]:
var=np.array([2,3,6,2])
var_mod=var%2
print(var_mod)

[0 1 0 0]


# 2D Array

In [16]:
x1=np.array([[1,2,3,4],[5,6,7,8]])
x2=np.array([[4,3,2,1],[8,7,6,5]])

x=x1+x2
print(x)


[[ 5  5  5  5]
 [13 13 13 13]]
