# Slicing

In [8]:
import numpy as np

In [9]:
var=np.array([1,2,3,4,5,6,7,8,9,10])
print(var[1:5])

[2 3 4 5]


In [11]:
print(var[1:6])

[2 3 4 5 6]


In [12]:
print(var[:8])

[1 2 3 4 5 6 7 8]


In [13]:
print(var[1:])

[ 2  3  4  5  6  7  8  9 10]


In [14]:
print(var[:5])

[1 2 3 4 5]


In [18]:
print(var[-2:-1])

[9]


In [19]:
print(var[-8:-2])

[3 4 5 6 7 8]


# 2D Array

In [23]:
var1 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(var1[1, 1:3])

[7 8]


In [24]:
var1 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(var1[0:2, 4])

[ 5 10]


In [25]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [26]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:2])

[1 2]
